---
- name: ensure ssh is installed
  apt: pkg=openssh-server state=installed

- name: disable remote login as root
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin " line="PermitRootLogin no"
  notify:
    - restart sshd

- name: disable dsa/ecdsa host keys
  lineinfile: dest=/etc/ssh/sshd_config regexp="^\s*?HostKey\s+/etc/ssh/ssh_host_(ec)?dsa_key\b" state=absent

- name: ensure ssh is enabled and running
  service: name=ssh enabled=yes state=running
